version: '3.5'
services:
  b2bdb:
    image: "postgres:13"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: b2b
    volumes:
      - ./init-scripts/init_b2bdb.sql:/docker-entrypoint-initdb.d/init_b2bdb.sql
      - ./init-scripts/:/docker-entrypoint-initdb.d/
    restart: always
    container_name: b2bdb
    hostname: b2bdb
    healthcheck:
      test: ["CMD","pg_is_ready","-U","b2b"]
      interval: 5s
      retries: 5
    networks:
      - airflow

  scheduler:
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw

  webserver:
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw

  triggerer:
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw

  metabase:
    image: metabase/metabase:v0.46.6.4
    volumes:
      - ./include/metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - 3000:3000
    restart: always